package lab1

import NeedlemanWunsch
import org.junit.jupiter.api.Test

internal class NeedlemanWunschTest {

    @Test
    fun test1() {
        val gap = -5
        val matchFile = "src/main/kotlin/lab1/BLOSUM62.txt"
        val seqA = "MSTAGKVIKCKAAVLWELHKPFTIEDIEVAPPKAHEVRIKMVATGVCRSDDHVVSGTLVTPLPAVLGHEGAGIVE" +
                "SVGEGVTCVKPGDKVIPLFSPQCGECRICKHPESNFCSRSDLLMPRGTLREGTSRFSCKGKQIHNFISTSTFSQY" +
                "TVVDDIAVAKIDGASPLDKVCLIGCGFSTGYGSAVKVAKVTPGSTCAVFGLGGVGLSVIIGCKAAGAARIIAVDI" +
                "NKDKFAKAKELGATECINPQDYSKPIQEVLQEMTDGGVDFSFEVIGRLDTMTSALLSCHAACGVSVVVGVPPNAQ" +
                "NLSMNPMLLLLGRTWKGAIFGGFKSKDSVPKLVADFMAKKFPLDPLITHVLPFEKINEAFDLLRSGKSIRTVLTF"
        val seqB = "MSTAGKVIKCKAAVLWELKKPFSIEEVEVAPPKAHEVRIKMVAVGICGTDDHVVSGTMVTPLPVILGHEAAGIVE" +
                "SVGEGVTTVKPGDKVIPLAIPQCGKCRICKNPESNYCLKNDVSNPQGTLQDGTSRFTCRRKPIHHFLGISTFSQY" +
                "TVVDENAVAKIDAASPLEKVCLIGCGFSTGYGSAVNVAKVTPGSTCAVFGLGGVGLSAIMGCKAAGAARIIAVDI" +
                "NKDKFAKAKELGATECINPQDYKKPIQEVLKEMTDGGVDFSFEVIGRLDTMMASLLCCHEACGTSVIVGVPPDSQ" +
                "NLSMNPMLLLTGRTWKGAILGGFKSKECVPKLVADFMAKKFSLDALITHV"

        val result = NeedlemanWunsch(seqA, seqB, gap, matchFile)

        assert(result.first == 1429)
        assert(result.second != null)
        assert(result.second!!.first ==  "MSTAGKVIKCKAAVLWELHKPFTIEDIEVAPPKAHEVRIKMVATGVCRSDDHVVSGTLVTPLPAVLGHEGAGIVESVGEGVTCVKPGDKVIPLFSPQCGECRICKHPESNFCSRSDLLMPRGTLREGTSRFSCKGKQIHNFISTSTFSQYTVVDDIAVAKIDGASPLDKVCLIGCGFSTGYGSAVKVAKVTPGSTCAVFGLGGVGLSVIIGCKAAGAARIIAVDINKDKFAKAKELGATECINPQDYSKPIQEVLQEMTDGGVDFSFEVIGRLDTMTSALLSCHAACGVSVVVGVPPNAQNLSMNPMLLLLGRTWKGAIFGGFKSKDSVPKLVADFMAKKFPLDPLITHVLPFEKINEAFDLLRSGKSIRTVLTF")
        assert(result.second!!.second == "MSTAGKVIKCKAAVLWELKKPFSIEEVEVAPPKAHEVRIKMVAVGICGTDDHVVSGTMVTPLPVILGHEAAGIVESVGEGVTTVKPGDKVIPLAIPQCGKCRICKNPESNYCLKNDVSNPQGTLQDGTSRFTCRRKPIHHFLGISTFSQYTVVDENAVAKIDAASPLEKVCLIGCGFSTGYGSAVNVAKVTPGSTCAVFGLGGVGLSAIMGCKAAGAARIIAVDINKDKFAKAKELGATECINPQDYKKPIQEVLKEMTDGGVDFSFEVIGRLDTMMASLLCCHEACGTSVIVGVPPDSQNLSMNPMLLLTGRTWKGAILGGFKSKECVPKLVADFMAKKFSLDALITH----------------------V---")
    }

    @Test
    fun test2() {
        val gap = -2
        val matchFile = "src/main/kotlin/lab1/BLOSUM62.txt"
        val seqA = "AATCG"
        val seqB = "AACG"

        val result = NeedlemanWunsch(seqA, seqB, gap, matchFile)

        assert(result.first == 21)
        assert(result.second != null)
        assert(result.second!!.first ==  "AATCG")
        assert(result.second!!.second == "AA-CG")
    }

    @Test
    fun test3() {
        val gap = -2
        val matchFile = "src/main/kotlin/lab1/BLOSUM62.txt"
        val seqA = "SPETVIHSGWVIWRELFSHWPDQCKLLFGDWFAWIHWTYLVYYSAGPPCQGQSDIVVMMQ" +
                "KKLRTNFCQCYKYWYQ"
        val seqB = "SPSDQFFTVIHSCLYWVIWRDLMSHLFMNGAAIDIHWTWDSIAIGPPLVYPIEEVFAGPS" +
                "TIVVMMQKMLRTNFCQCYKPWYQ"

        val result = NeedlemanWunsch(seqA, seqB, gap, matchFile)

        assert(result.first == 217)
        assert(result.second != null)
        assert(result.second!!.first ==  "SP-E---TVIHSG--WVIWRELFSHWPDQCKLLF--GDWFAW-IHWTYLVYYS-A-GPPC----Q----GQSDIVVMMQKKLRTNFCQCYKYWYQ")
        assert(result.second!!.second == "SPSDQFFTVIHSCLYWVIWRDLMSH-------LFMNG--AAIDIHWT---WDSIAIGPPLVYPIEEVFAGPSTIVVMMQKMLRTNFCQCYKPWYQ")
    }
}